### ISSUE TITLE
Remove visibility getter/setter in BasicView

### ISSUE THREAD

**Issue by aliokan** [DoclerLabs/hexMVC#13]
[BasicView](https://github.com/DoclerLabs/hexMVC/blob/master/src/hex/view/BasicView.hx) should be align with [IView](https://github.com/DoclerLabs/hexMVC/blob/master/src/hex/view/IView.hx). ;)

**Comment by FrancisBourre** [comment]
This issue was moved to DoclerLabs/hexMachina#62
