### ISSUE TITLE
Keep API consistency in CommandMappings

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexMVC#4]
We have inconsistent usage of the followings:

```
function withPayloads( payloads : Array<ExecutionPayload> ) : ICommandMapping;
function withCompleteHandlers( handler : AsyncHandler ) : ICommandMapping;
```

As you see the withPayloads waits for an array of ExecutionPayload, and the withCompleteHandlers waits only for one AsyncHandler.

It should wait arrays or single ones all the time

**Comment by FrancisBourre** [comment]
This issue was moved to DoclerLabs/hexMachina#57
