### ISSUE TITLE
request parameter should be optional in commands

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexMVC#6]
now MacroExecutor force request property in commands even if there is nothing.
It should be changed to something like this in Macroexecutor:
Reflect.callMethod( command, Reflect.field( command, command.executeMethodName ), request != null ? [ request ]  : [] );

**Comment by FrancisBourre** [comment]
Yup, you're right, and we got the same problem in [CommandExecutor](https://github.com/DoclerLabs/hexMVC/blob/c703f087f801f026c7bff00a4b316cef05c493d3/src/hex/control/command/CommandExecutor.hx#L83)
